Ini, TOML
# Allow logged-in users with the 'admin' role to view /private/
[[redirects]]
  from = "/private/*"
  status = 200
  conditions = {Role = ["admin"]}

# Redirect unauthenticated visitors back to homepage
[[redirects]]
  from = "/private/*"
  to = "/"
  status = 302
  force = true
